name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:       # Allows you to click "Run workflow" manually
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Generate the Snake (Pacman)
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3. Create dist directory and move the file there (CRITICAL STEP)
      - name: Move to dist
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/

      # 4. Push the SVG to the output branch
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}